// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiABi4QF_nOWZ4mh256dGOTO_F0VcZlOQ',
    appId: '1:20683770:web:4372c7c8d973c17084e243',
    messagingSenderId: '20683770',
    projectId: 'torrefactor-e13dc',
    authDomain: 'torrefactor-e13dc.firebaseapp.com',
    databaseURL: 'https://torrefactor-e13dc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'torrefactor-e13dc.appspot.com',
    measurementId: 'G-MY7MKLR3L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM6IlQTSG_Iv4GqUndIh0WffAfdUvnMu4',
    appId: '1:20683770:android:f8579f12dd9c496a84e243',
    messagingSenderId: '20683770',
    projectId: 'torrefactor-e13dc',
    databaseURL: 'https://torrefactor-e13dc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'torrefactor-e13dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2CAT-oBnUEp1ReQ3uQ8To9MoiJHsfjcY',
    appId: '1:20683770:ios:cb7ed907ba9f0def84e243',
    messagingSenderId: '20683770',
    projectId: 'torrefactor-e13dc',
    databaseURL: 'https://torrefactor-e13dc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'torrefactor-e13dc.appspot.com',
    iosClientId: '20683770-4qkl609pseuvvfq8c0jhau8r223ttssc.apps.googleusercontent.com',
    iosBundleId: 'com.example.torrefactor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2CAT-oBnUEp1ReQ3uQ8To9MoiJHsfjcY',
    appId: '1:20683770:ios:cb7ed907ba9f0def84e243',
    messagingSenderId: '20683770',
    projectId: 'torrefactor-e13dc',
    databaseURL: 'https://torrefactor-e13dc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'torrefactor-e13dc.appspot.com',
    iosClientId: '20683770-4qkl609pseuvvfq8c0jhau8r223ttssc.apps.googleusercontent.com',
    iosBundleId: 'com.example.torrefactor',
  );
}
